version: '3.8'

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /mnt/influx_data:/var/lib/influxdb2
    environment:
      # InfluxDB-Initialisierung
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345
      - DOCKER_INFLUXDB_INIT_ORG=WDBK-Projekt
      - DOCKER_INFLUXDB_INIT_BUCKET=db_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=WDBK-Token

  data_collector:
    build: ./collector
    container_name: data_collector
    depends_on:
      - influxdb
    environment:
      # DB Marketplace API
      - DB_CLIENT_ID=d8b5722806090d7f7f91d83f470e97a15
      - DB_API_KEY=6c174890c3f7e90719e8b1e4da0851cf

      # WeatherAPI
      - WEATHER_API_KEY=f42748087e4643ec992205222253105

      # InfluxDB-Zugriff für Collector
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=mein-myToken
      - INFLUXDB_ORG=meineOrganisation
      - INFLUXDB_BUCKET=db_data
      
    restart: always

volumes:
  influxdb_data: {}

